theme = "jetbrains_dark"

[editor]
line-number = "relative"
mouse = false
auto-save = true
# bufferline = "always"
scrolloff = 15
color-modes = true
popup-border = "none"
preview-completion-insert = false
indent-heuristic = "tree-sitter"
soft-wrap = { enable = true }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = 	["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]

[editor.whitespace]
render.tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[keys.insert]
j.k = "normal_mode"
